package UI;

import BEAN.Diagnostico;
import DAO.DiagnosticoDAO;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Util;

public class DiagnosticosFrm extends javax.swing.JFrame {
    DiagnosticoDAO diaDAO;
    DefaultTableModel dtm;
    boolean sw = false;
    String cad = "";
    int idemp;
    public DiagnosticosFrm(int mdiH, int mdiW) {
        diaDAO = new DiagnosticoDAO();
        int slx, sly, wd = mdiW, hd = mdiH;
        
        ///Centrando el internalFrame para una mejor visualizacion///
      
        this.setSize(386, 350);
        slx = (wd/2) - (386/2);
        sly = (hd/2) -(350/2);
        this.setLocation(slx, sly);
        this.setResizable(false);
        ///Centrando el internalFrame para una mejor visualizacion///

        
        initComponents();

        dtm=(DefaultTableModel)tblDiagnostico.getModel();
        llenaTabla(sw, cad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDiagnostico = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBusq = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxaDescripcion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel3.setLayout(null);

        tblDiagnostico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDiagnostico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDiagnosticoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDiagnostico);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(0, 50, 330, 140);

        jLabel2.setText("Criterios de búsqueda:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 10, 120, 15);

        txtBusq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusqActionPerformed(evt);
            }
        });
        txtBusq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusqKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusqKeyReleased(evt);
            }
        });
        jPanel3.add(txtBusq);
        txtBusq.setBounds(130, 10, 190, 19);

        jTabbedPane1.addTab("Consulta", jPanel3);

        jPanel4.setLayout(null);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(null);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel5.add(btnRegistrar);
        btnRegistrar.setBounds(30, 150, 120, 25);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel5.add(btnLimpiar);
        btnLimpiar.setBounds(170, 150, 100, 25);

        jLabel7.setText("Descripcion");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(20, 40, 60, 20);

        TxaDescripcion.setColumns(20);
        TxaDescripcion.setRows(5);
        jScrollPane2.setViewportView(TxaDescripcion);

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(110, 0, 223, 100);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(10, 10, 320, 180);

        jTabbedPane1.addTab("Nuevo", jPanel4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(20, 110, 960, 530);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Diagnósticos");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 40, 1000, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDiagnosticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDiagnosticoMouseClicked
        if(evt.getClickCount()==1){
            jTabbedPane1.setSelectedIndex(1);
            llenaModifica();
        }
    }//GEN-LAST:event_tblDiagnosticoMouseClicked

    private void txtBusqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusqActionPerformed

    private void txtBusqKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusqKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusqKeyPressed

    private void txtBusqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusqKeyReleased
                LimpiaTabla();
        boolean swt;
        String x = txtBusq.getText();
        if(x.isEmpty()){
            swt = false;
        }else{
            swt = true;
        }
        llenaTabla(swt, x);
    }//GEN-LAST:event_txtBusqKeyReleased

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String proc = btnRegistrar.getText();
        int id = 0, est,tipo;
        String pr= "";
        if(valida() == true){
            Util u = new Util();
            Diagnostico p = new Diagnostico();
            p.setDiag_desc(this.TxaDescripcion.getText());
            if (proc.equals("Registrar")){
                id = u.idNext("Diagnosticos", "id_diagnostico");
                pr = "insert";
            }
            if(proc.equals("Actualizar")){
                id = idemp;
                pr = "update";
            }
            p.setId_diagnostico(id);
            diaDAO.registrarDiagnostico(p, pr);
            limpiaControl();
            LimpiaTabla();
            llenaTabla(false, "");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

                limpiaControl();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged

    }//GEN-LAST:event_jTabbedPane1StateChanged

private void llenaTabla(boolean swr, String cadr) {
         Vector<Diagnostico> diagDao = diaDAO.listarDiagnosticos(swr, cadr);
         int i =  diagDao.size();

         for(int j = 0; j<diagDao.size();j++){
            Vector vect = new Vector();
            vect.addElement(diagDao.get(j).getId_diagnostico());
            vect.addElement(diagDao.get(j).getDiag_desc());
            
            dtm.addRow(vect);
        }
    }
private void limpiaControl(){
        
        TxaDescripcion.setText("");
        btnRegistrar.setText("Registrar");
        TxaDescripcion.requestFocus();
    }
    private boolean valida(){
        boolean sw = false;
            if(TxaDescripcion.getText().equals("")){
                sw = false;
                JOptionPane.showMessageDialog(this, "Debe registrar Descripcion de la Diagnotico ","Módulo de aplicación Diagnotico",JOptionPane.ERROR_MESSAGE);
                TxaDescripcion.requestFocusInWindow();
            }else{
                sw = true;
            }
        return sw;
    }



    private void llenaModifica(){
        int est;
        String cadX;
        int fila = tblDiagnostico.getSelectedRow();
        idemp = Integer.parseInt((dtm.getValueAt(fila, 0)).toString().trim());
        TxaDescripcion.setText(((String)dtm.getValueAt(fila, 1)).trim());
        
        
        btnRegistrar.setText("Actualizar");
    }

    public void LimpiaTabla(){
    DefaultTableModel dm=(DefaultTableModel)tblDiagnostico.getModel();
    if(dm.getRowCount()>0){
        while(dm.getRowCount()>0){
            dm.removeRow(dm.getRowCount()-1);
        }
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxaDescripcion;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblDiagnostico;
    private javax.swing.JTextField txtBusq;
    // End of variables declaration//GEN-END:variables
}
