package UI;

import BEAN.Falla;
import DAO.EmpleadoDAO;
import DAO.FallaDAO;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Util;

public class FallasFrm extends javax.swing.JFrame {
    FallaDAO falDAO;
    DefaultTableModel dtm;
    boolean sw = false;
    String cad = "";
    int idemp;
    
  public FallasFrm(int mdiH, int mdiW) {
        falDAO = new FallaDAO();
        int slx, sly, wd = mdiW, hd = mdiH;
        
        ///Centrando el internalFrame para una mejor visualizacion///
      
        this.setSize(386, 350);
        slx = (wd/2) - (386/2);
        sly = (hd/2) -(350/2);
        this.setLocation(slx, sly);
        this.setResizable(false);
        ///Centrando el internalFrame para una mejor visualizacion///

        
        initComponents();

        dtm=(DefaultTableModel)tblPersonal.getModel();
        llenaTabla(sw, cad);
    }
    private void llenaTabla(boolean swr, String cadr) {
         Vector<Falla> fallDao = falDAO.listarFallas(swr, cadr);
         int i =  fallDao.size();

         for(int j = 0; j<fallDao.size();j++){
            Vector vect = new Vector();
            vect.addElement(fallDao.get(j).getId_falla());
            vect.addElement(fallDao.get(j).getTipo_falla());
            vect.addElement(fallDao.get(j).getFalla_desc());
            
            dtm.addRow(vect);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersonal = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBusq = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtTipo = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxaDescripcion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel3.setLayout(null);

        tblPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Tipo", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPersonalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPersonal);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(0, 50, 330, 140);

        jLabel2.setText("Criterios de búsqueda:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 10, 120, 15);

        txtBusq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusqActionPerformed(evt);
            }
        });
        txtBusq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusqKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusqKeyReleased(evt);
            }
        });
        jPanel3.add(txtBusq);
        txtBusq.setBounds(130, 10, 190, 19);

        jTabbedPane1.addTab("Consulta", jPanel3);

        jPanel4.setLayout(null);
        jPanel4.add(txtTipo);
        txtTipo.setBounds(110, 10, 160, 19);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel4.add(btnRegistrar);
        btnRegistrar.setBounds(30, 150, 120, 25);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel4.add(btnLimpiar);
        btnLimpiar.setBounds(170, 150, 100, 25);

        jLabel6.setText("Tipo");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(30, 10, 40, 15);

        jLabel7.setText("Area");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(30, 70, 50, 20);

        TxaDescripcion.setColumns(20);
        TxaDescripcion.setRows(5);
        jScrollPane2.setViewportView(TxaDescripcion);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(110, 40, 223, 100);

        jTabbedPane1.addTab("Nueva", jPanel4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(20, 110, 960, 530);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fallas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 40, 1000, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPersonalMouseClicked
        if(evt.getClickCount()==1){
            jTabbedPane1.setSelectedIndex(1);
            llenaModifica();
        }
    }//GEN-LAST:event_tblPersonalMouseClicked

    private void txtBusqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusqActionPerformed

    private void txtBusqKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusqKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusqKeyPressed

    private void txtBusqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusqKeyReleased
        LimpiaTabla();
        boolean swt;
        String x = txtBusq.getText();
        if(x.isEmpty()){
            swt = false;
        }else{
            swt = true;
        }
        llenaTabla(swt, x);
    }//GEN-LAST:event_txtBusqKeyReleased

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String proc = btnRegistrar.getText();
        int id = 0, est,tipo;
        String pr= "";
        if(valida() == true){
            Util u = new Util();
            Falla p = new Falla();
            p.setTipo_falla(txtTipo.getText());
            p.setFalla_desc(this.TxaDescripcion.getText());

            if (proc.equals("Registrar")){
                id = u.idNext("Fallas", "id_falla");
                pr = "insert";
            }
            if(proc.equals("Actualizar")){
                id = idemp;
                pr = "update";
            }
            p.setId_falla(id);
            falDAO.registrarEquipo(p, pr);
            limpiaControl();
            LimpiaTabla();
            llenaTabla(false, "");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        limpiaControl();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged

    }//GEN-LAST:event_jTabbedPane1StateChanged

 private void limpiaControl(){
        txtTipo.setText("");
        TxaDescripcion.setText("");
        btnRegistrar.setText("Registrar");
        txtTipo.requestFocus();
    }
    private boolean valida(){
        boolean sw = false;
        if(txtTipo.getText().equals("")){
            sw = false;
            JOptionPane.showMessageDialog(this, "Debe registrar TIPO de FALLA","Módulo de aplicación FALLAS",JOptionPane.ERROR_MESSAGE);
            txtTipo.requestFocusInWindow();
        }else{

            if(TxaDescripcion.getText().equals("")){
                sw = false;
                JOptionPane.showMessageDialog(this, "Debe registrar Descripcion de la falla ","Módulo de aplicación FALLA",JOptionPane.ERROR_MESSAGE);
                TxaDescripcion.requestFocusInWindow();
            }else{
                sw = true;
            }
        }
        return sw;
    }



    private void llenaModifica(){
        int est;
        String cadX;
        int fila = tblPersonal.getSelectedRow();
        txtTipo.setText(((String)dtm.getValueAt(fila, 1)).trim());
        TxaDescripcion.setText(((String)dtm.getValueAt(fila, 2)).trim());
        idemp = Integer.parseInt((dtm.getValueAt(fila, 0)).toString().trim());
        btnRegistrar.setText("Actualizar");
    }

    public void LimpiaTabla(){
    DefaultTableModel dm=(DefaultTableModel)tblPersonal.getModel();
    if(dm.getRowCount()>0){
        while(dm.getRowCount()>0){
            dm.removeRow(dm.getRowCount()-1);
        }
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxaDescripcion;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblPersonal;
    private javax.swing.JTextField txtBusq;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
