package UI;

import BEAN.Repuesto;
import DAO.RepuestoDAO;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Util;

public class RepuestosFrm extends javax.swing.JFrame {


    RepuestoDAO repDAO;
    DefaultTableModel dtm;
    boolean sw = false;
    String cad = "";
    int idemp;
    public RepuestosFrm(int mdiH, int mdiW) {
        repDAO = new RepuestoDAO();
        int slx, sly, wd = mdiW, hd = mdiH;
        
        ///Centrando el internalFrame para una mejor visualizacion///
      
        this.setSize(386, 350);
        slx = (wd/2) - (386/2);
        sly = (hd/2) -(350/2);
        this.setLocation(slx, sly);
        this.setResizable(false);
        ///Centrando el internalFrame para una mejor visualizacion///

        
        initComponents();

        dtm=(DefaultTableModel)tblRespuesto.getModel();
        llenaTabla(sw, cad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRespuesto = new javax.swing.JTable();
        txtBusq = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxaDescripcion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel3.setLayout(null);

        tblRespuesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Descripcion", "Costo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRespuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRespuestoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRespuesto);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(25, 100, 900, 310);

        txtBusq.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtBusq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusqActionPerformed(evt);
            }
        });
        txtBusq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusqKeyReleased(evt);
            }
        });
        jPanel3.add(txtBusq);
        txtBusq.setBounds(305, 30, 200, 30);

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel8.setText("Búsqueda por descripción");
        jLabel8.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel8AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel3.add(jLabel8);
        jLabel8.setBounds(25, 30, 209, 30);

        jButton2.setText("Editar");
        jPanel3.add(jButton2);
        jButton2.setBounds(400, 430, 150, 50);

        jTabbedPane1.addTab("Consulta", jPanel3);

        jPanel4.setLayout(null);

        jLabel7.setText("Descripción");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(30, 30, 100, 30);

        TxaDescripcion.setColumns(20);
        TxaDescripcion.setRows(5);
        jScrollPane2.setViewportView(TxaDescripcion);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(160, 30, 223, 100);

        jLabel6.setText("Costo unitario");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(30, 150, 100, 30);
        jPanel4.add(txtCosto);
        txtCosto.setBounds(160, 150, 220, 30);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel4.add(btnRegistrar);
        btnRegistrar.setBounds(500, 430, 150, 50);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel4.add(btnLimpiar);
        btnLimpiar.setBounds(330, 430, 150, 50);

        jTabbedPane1.addTab("Nuevo", jPanel4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(20, 110, 960, 530);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Repuestos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 40, 1000, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblRespuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRespuestoMouseClicked
        if(evt.getClickCount()==1){
            jTabbedPane1.setSelectedIndex(1);
            llenaModifica();
        }
    }//GEN-LAST:event_tblRespuestoMouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged

    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void txtBusqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusqActionPerformed

    }//GEN-LAST:event_txtBusqActionPerformed

    private void txtBusqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusqKeyReleased
        dtm.setRowCount(0);

        String filtro = txtBusq.getText();
        if(filtro.isEmpty()) {
            llenaTabla(false, "");
        } else {
            llenaTabla(true, filtro);
        }
    }//GEN-LAST:event_txtBusqKeyReleased

    private void jLabel8AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel8AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8AncestorAdded

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String proc = btnRegistrar.getText();
        int id = 0, est, tipo;
        String pr= "";
        
        if(valida() == true){
            Util u = new Util();
            Repuesto p = new Repuesto();
            p.setCosto_unitario(Float.parseFloat(txtCosto.getText()));
            p.setRep_desc(this.TxaDescripcion.getText());
            
            if (proc.equals("Registrar")) {
                id = u.idNext("Repuestos", "id_repuesto");
                pr = "insert";
            }
            
            if(proc.equals("Actualizar")) {
                id = idemp;
                pr = "update";
            }
            
            p.setId_repuesto(id);
            repDAO.registrarRespuesto(p, pr);
            limpiaControl();
            LimpiaTabla();
            llenaTabla(false, "");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiaControl();
    }//GEN-LAST:event_btnLimpiarActionPerformed
private void llenaTabla(boolean swr, String cadr) {
         Vector<Repuesto> RespuestoDao = repDAO.listarRepuestos(swr, cadr);
         int i =  RespuestoDao.size();

         for(int j = 0; j<RespuestoDao.size();j++){
            Vector vect = new Vector();
            vect.addElement(RespuestoDao.get(j).getId_repuesto());
            vect.addElement(RespuestoDao.get(j).getRep_desc());
            vect.addElement(RespuestoDao.get(j).getCosto_unitario()+"");
            
            dtm.addRow(vect);
        }
    }
private void limpiaControl(){
        txtCosto.setText("");
        TxaDescripcion.setText("");
        btnRegistrar.setText("Registrar");
        txtCosto.requestFocus();
    }
    private boolean valida(){
        boolean sw = false;
        if(txtCosto.getText().equals("")){
            sw = false;
            JOptionPane.showMessageDialog(this, "Debe registrar Costo de Respuesto","Módulo de aplicación Repuesto",JOptionPane.ERROR_MESSAGE);
            txtCosto.requestFocusInWindow();
        }else{

            if(TxaDescripcion.getText().equals("")){
                sw = false;
                JOptionPane.showMessageDialog(this, "Debe registrar Descripcion de la Repuesto ","Módulo de aplicación Repuesto",JOptionPane.ERROR_MESSAGE);
                TxaDescripcion.requestFocusInWindow();
            }else{
                sw = true;
            }
        }
        return sw;
    }



    private void llenaModifica(){
        int est;
        String cadX;
        int fila = tblRespuesto.getSelectedRow();
        idemp = Integer.parseInt((dtm.getValueAt(fila, 0)).toString().trim());
        TxaDescripcion.setText(((String)dtm.getValueAt(fila, 1)).trim());
        txtCosto.setText((String) dtm.getValueAt(fila, 2));
        
        
        btnRegistrar.setText("Actualizar");
    }

    public void LimpiaTabla(){
    DefaultTableModel dm=(DefaultTableModel)tblRespuesto.getModel();
    if(dm.getRowCount()>0){
        while(dm.getRowCount()>0){
            dm.removeRow(dm.getRowCount()-1);
        }
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxaDescripcion;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblRespuesto;
    private javax.swing.JTextField txtBusq;
    private javax.swing.JTextField txtCosto;
    // End of variables declaration//GEN-END:variables
}
